### ISSUE TITLE
Error - Development server does not run for me

### ISSUE THREAD

**Issue by lukyncze** [JetBrains/webteam-test#38]
Hello, I tried running this project and I got a nasty errors instead of running dev server :/

I am using:
**Ubuntu 22.04.2 LTS, 64-bit
Node v18.11.0**

I tried installing dependencies with npm, yarn and also pnpm, neither of them did work.

Could someone help me with this please?

Thank you in advance!

**These are error messages I got:**

```
yarn start
yarn run v1.22.19
$ cross-env NODE_ENV=development webpack-dev-server --port 5050
ℹ ｢wds｣: Project is running at http://localhost:5050/
ℹ ｢wds｣: webpack output is served from /
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/lusu/Desktop/webteam-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/lusu/Desktop/webteam-test/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/lusu/Desktop/webteam-test/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/lusu/Desktop/webteam-test/node_modules/babel-loader/lib/index.js:51:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.11.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**And here a history of commands I wrote in the console:**

```
2000  git clone https://github.com/JetBrains/webteam-test
2001  cd webteam-test/
2002  yarn install
2003  yarn start
2004  history
```

**Comment by IPogorelova** [comment]
Hello @lukyncze 👋

At the moment this project won't build with Node version higher than 16.x.
Please check Node 16.17.0 (this version works perfectly for me) and if it's all ok - drop a message here and I'll close this issue.

P.S.: I've added a note about this to [README.md](https://github.com/JetBrains/webteam-test#running-a-project). Thank you for the feedback!

**Comment by lukyncze** [comment]
Hello @IPogorelova,

thank you for the feedback! I really did not know, why it was not working for me. I will try it ASAP :)

**Comment by lukyncze** [comment]
It works on Node 16.17.0 for me. Thanks one more time :)
